version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "00:00"
    open-pull-requests-limit: 0
    ignore:
    - dependency-name: sphinx
      versions:
      - ">= 5.3.0"
    - dependency-name: celery[redis]
      versions:
      - ">= 5.2.7"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "01:00"
    open-pull-requests-limit: 0
    ignore:
    - dependency-name: cypress
      versions:
      - ">= 11.2.0"
