from modelchoices import Choices


class EnquiryStage(Choices):
    NEW = ("NEW", "New")
    AWAITING_RESPONSE = ("AWAITING_RESPONSE", "Awaiting response from Investor")
    NON_RESPONSIVE = ("NON_RESPONSIVE", "Non-responsive")
    NON_FDI = ("NON_FDI", "Non-FDI")
    ADDED_TO_DATAHUB = ("ADDED_TO_DATAHUB", "Added to Data Hub")
    SENT_TO_POST = ("SENT_TO_POST", "Sent to Post")
    POST_PROGRESSING = ("POST_PROGRESSING", "Post progressing")


class InvestmentReadiness(Choices):
    DEFAULT = ("DEFAULT", "----")
    CONVINCED = (
        "CONVINCED",
        "I’m convinced and want to talk to someone about my plans",
    )
    SHORTLIST = (
        "SHORTLIST",
        "The UK is on my shortlist. How can the Department for International Trade help me?",
    )
    EXPLORING = (
        "EXPLORING",
        "I’m still exploring where to expand my business and would like to know more about the UK’s offer",
    )
    NOT_READY = ("NOT_READY", "I’m not yet ready to invest. Keep me informed")


class Quality(Choices):
    DEFAULT = ("DEFAULT", "----")
    JUNK = ("JUNK", "Junk")
    NON_FDI = ("NON_FDI", "Non-FDI / Potentially Non-FDI")
    POTENTIAL_FDI = ("POTENTIAL_FDI", "Potentially FDI")
    LIKELY_FDI = ("LIKELY_FDI", "FDI / likely FDI")


class MarketingChannel(Choices):
    DEFAULT = ("DEFAULT", "----")
    LINKEDIN = ("LINKEDIN", "LinkedInLeadGen")
    CHOGM = ("CHOGM", "CHOGM")
    IIGB = ("IIGB", "IiGB")
    IIGB_LINKEDIN = ("IIGB_LINKEDIN", "IiGB (LinkedIn)")
    HPO = ("HPO", "HPO")
    B2B = ("B2B", "B2B")
    EBOOK = ("EBOOK", "EBOOK - Worldwide")
    TRA = ("TRA", "TRA")
    ENCORE = ("ENCORE", "Encore")
    OTHER = ("OTHER", "Other")


class HowDidTheyHear(Choices):
    DEFAULT = ("DEFAULT", "----")
    PRESS_AD = ("PRESS_AD", "Press ad (newspaper/trade publication")
    OUTDOOR_AD = ("OUTDOOR_AD", "Outdoor ad/billboard")
    LINKEDIN = ("LINKEDIN", "LinkedIn")
    SOCIAL_MEDIA = ("SOCIAL_MEDIA", "Other social media (e.g. Twitter/Facebook)")
    INTERNET_SEARCH = ("INTERNET_SEARCH", "Internet search")
    OTHER = ("OTHER", "Other")


class PrimarySector(Choices):
    DEFAULT = ("DEFAULT", "----")
    ADVANCED_ENG = ("ADVANCED_ENG", "Advanced Engineering")
    AEROSPACE = ("AEROSPACE", "Aerospace")
    AGRICULTURE = ("AGRICULTURE,", "Agriculture, Horticulture, Fisheries & Pets")
    AIRPORTS = ("AIRPORTS", "Airports")
    AUTOMOTIVE = ("AUTOMOTIVE", "Automotive")
    CHEMICALS = ("CHEMICALS", "Chemicals")
    CONSTRUCTION = ("CONSTRUCTION", "Construction")
    CONSUMER = ("CONSUMER", "Consumer & Retail")
    CREATIVE = ("CREATIVE", "Creative Industries")
    CYBER = ("CYBER", "Cyber Security")
    DEFENCE = ("DEFENCE", "Defence")
    EDUCATION = ("EDUCATION", "Education & Training")
    ENERGY = ("ENERGY", "Energy")
    ENVIRONMENT = ("ENVIRONMENT", "Environment")
    FINANCIAL = ("FINANCIAL", "Financial & Professional Services")
    FOOD = ("FOOD", "Food & Drink")
    HEALTHCARE = ("HEALTHCARE", "Healthcare Services")
    MARITIME = ("MARITIME", "Maritime")
    MEDICAL = ("MEDICAL", "Medical Devices & Equipment")
    MINING = ("MINING", "Mining")
    PHARMACEUTICALS = ("PHARMACEUTICALS", "Pharmaceuticals & Biotechnology")
    RAILWAYS = ("RAILWAYS", "Railways")
    SECURITY = ("SECURITY", "Security")
    SPACE = ("SPACE", "Space")
    SPORTS = ("SPORTS", "Sports Economy")
    TECHNOLOGY = ("TECHNOLOGY", "Technology & Smart Cities")
    WATER = ("WATER", "Water")


class IstSector(Choices):
    DEFAULT = ("DEFAULT", "----")
    ITECH = ("ITECH", "ITECH")
    LIFE = ("LIFE", "Life Science")
    ENERGY = ("ENERGY", "Energy & Environment")
    BPFS = ("BPFS", "BPFS")
    AEM = ("AEM", "AEM")
    UNCLASSIFIED = ("UNCLASSIFIED", "Unclassified")


class Country(Choices):
    DEFAULT = ("DEFAULT", "----")
    AFGHANISTAN = ("AFGHANISTAN", "Afghanistan")
    ALBANIA = ("ALBANIA", "Albania")
    ALGERIA = ("ALGERIA", "Algeria")
    ANDORRA = ("ANDORRA", "Andorra")
    ANGOLA = ("ANGOLA", "Angola")
    ANTIGUA = ("ANTIGUA", "Antigua and Barbuda")
    ARGENTINA = ("ARGENTINA", "Argentina")
    ARMENIA = ("ARMENIA", "Armenia")
    AUSTRALIA = ("AUSTRALIA", "Australia")
    AUSTRIA = ("AUSTRIA", "Austria")
    AZERBAIJAN = ("AZERBAIJAN", "Azerbaijan")
    BAHRAIN = ("BAHRAIN", "Bahrain")
    BANGLADESH = ("BANGLADESH", "Bangladesh")
    BARBADOS = ("BARBADOS", "Barbados")
    BELARUS = ("BELARUS", "Belarus")
    BELGIUM = ("BELGIUM", "Belgium")
    BELIZE = ("BELIZE", "Belize")
    BENIN = ("BENIN", "Benin")
    BHUTAN = ("BHUTAN", "Bhutan")
    BOLIVIA = ("BOLIVIA", "Bolivia")
    BOSNIA = ("BOSNIA", "Bosnia and Herzegovina")
    BOTSWANA = ("BOTSWANA", "Botswana")
    BRAZIL = ("BRAZIL", "Brazil")
    BRUNEI = ("BRUNEI", "Brunei")
    BULGARIA = ("BULGARIA", "Bulgaria")
    BURKINA = ("BURKINA", "Burkina Faso")
    BURUNDI = ("BURUNDI", "Burundi")
    CAMBODIA = ("CAMBODIA", "Cambodia")
    CAMEROON = ("CAMEROON", "Cameroon")
    CANADA = ("CANADA", "Canada")
    CAPE = ("CAPE", "Cape Verde")
    CENTRAL_AFRICA = ("CENTRAL_AFRICA", "Central African Republic")
    CHAD = ("CHAD", "Chad")
    CHILE = ("CHILE", "Chile")
    CHINA = ("CHINA", "China")
    COLOMBIA = ("COLOMBIA", "Colombia")
    COMOROS = ("COMOROS", "Comoros")
    CONGO = ("CONGO", "Congo")
    CONGO = ("CONGO", "Congo (Democratic Republic)")
    COSTA = ("COSTA", "Costa Rica")
    CROATIA = ("CROATIA", "Croatia")
    CUBA = ("CUBA", "Cuba")
    CYPRUS = ("CYPRUS", "Cyprus")
    CZECHIA = ("CZECHIA", "Czechia")
    CZECHOSLOVAKIA = ("CZECHOSLOVAKIA", "Czechoslovakia")
    DENMARK = ("DENMARK", "Denmark")
    DJIBOUTI = ("DJIBOUTI", "Djibouti")
    DOMINICA = ("DOMINICA", "Dominica")
    DOMINICAN = ("DOMINICAN", "Dominican Republic")
    EAST_GERMANY = ("EAST_GERMANY", "East Germany")
    EAST_TIMOR = ("EAST_TIMOR", "East Timor")
    ECUADOR = ("ECUADOR", "Ecuador")
    EGYPT = ("EGYPT", "Egypt")
    EL_SALVADOR = ("EL_SALVADOR", "El Salvador")
    GUINEA = ("GUINEA", "Equatorial Guinea")
    ERITREA = ("ERITREA", "Eritrea")
    ESTONIA = ("ESTONIA", "Estonia")
    ESWATINI = ("ESWATINI", "Eswatini")
    ETHIOPIA = ("ETHIOPIA", "Ethiopia")
    FIJI = ("FIJI", "Fiji")
    FINLAND = ("FINLAND", "Finland")
    FRANCE = ("FRANCE", "France")
    GABON = ("GABON", "Gabon")
    GEORGIA = ("GEORGIA", "Georgia")
    GERMANY = ("GERMANY", "Germany")
    GHANA = ("GHANA", "Ghana")
    GREECE = ("GREECE", "Greece")
    GRENADA = ("GRENADA", "Grenada")
    GUATEMALA = ("GUATEMALA", "Guatemala")
    GUINEA = ("GUINEA", "Guinea")
    GUINEA_BISSAU = ("GUINEA_BISSAU", "Guinea-Bissau")
    GUYANA = ("GUYANA", "Guyana")
    HAITI = ("HAITI", "Haiti")
    HONDURAS = ("HONDURAS", "Honduras")
    HUNGARY = ("HUNGARY", "Hungary")
    ICELAND = ("ICELAND", "Iceland")
    INDIA = ("INDIA", "India")
    INDONESIA = ("INDONESIA", "Indonesia")
    IRAN = ("IRAN", "Iran")
    IRAQ = ("IRAQ", "Iraq")
    IRELAND = ("IRELAND", "Ireland")
    ISRAEL = ("ISRAEL", "Israel")
    ITALY = ("ITALY", "Italy")
    IVORY = ("IVORY", "Ivory Coast")
    JAMAICA = ("JAMAICA", "Jamaica")
    JAPAN = ("JAPAN", "Japan")
    JORDAN = ("JORDAN", "Jordan")
    KAZAKHSTAN = ("KAZAKHSTAN", "Kazakhstan")
    KENYA = ("KENYA", "Kenya")
    KIRIBATI = ("KIRIBATI", "Kiribati")
    KOSOVO = ("KOSOVO", "Kosovo")
    KUWAIT = ("KUWAIT", "Kuwait")
    KYRGYZSTAN = ("KYRGYZSTAN", "Kyrgyzstan")
    LAOS = ("LAOS", "Laos")
    LATVIA = ("LATVIA", "Latvia")
    LEBANON = ("LEBANON", "Lebanon")
    LESOTHO = ("LESOTHO", "Lesotho")
    LIBERIA = ("LIBERIA", "Liberia")
    LIBYA = ("LIBYA", "Libya")
    LIECHTENSTEIN = ("LIECHTENSTEIN", "Liechtenstein")
    LITHUANIA = ("LITHUANIA", "Lithuania")
    LUXEMBOURG = ("LUXEMBOURG", "Luxembourg")
    MADAGASCAR = ("MADAGASCAR", "Madagascar")
    MALAWI = ("MALAWI", "Malawi")
    MALAYSIA = ("MALAYSIA", "Malaysia")
    MALDIVES = ("MALDIVES", "Maldives")
    MALI = ("MALI", "Mali")
    MALTA = ("MALTA", "Malta")
    MARSHALL = ("MARSHALL", "Marshall Islands")
    MAURITANIA = ("MAURITANIA", "Mauritania")
    MAURITIUS = ("MAURITIUS", "Mauritius")
    MEXICO = ("MEXICO", "Mexico")
    MICRONESIA = ("MICRONESIA", "Micronesia")
    MOLDOVA = ("MOLDOVA", "Moldova")
    MONACO = ("MONACO", "Monaco")
    MONGOLIA = ("MONGOLIA", "Mongolia")
    MONTENEGRO = ("MONTENEGRO", "Montenegro")
    MOROCCO = ("MOROCCO", "Morocco")
    MOZAMBIQUE = ("MOZAMBIQUE", "Mozambique")
    MYANMAR = ("MYANMAR", "Myanmar (Burma)")
    NAMIBIA = ("NAMIBIA", "Namibia")
    NAURU = ("NAURU", "Nauru")
    NEPAL = ("NEPAL", "Nepal")
    NETHERLANDS = ("NETHERLANDS", "Netherlands")
    NEW = ("NEW", "New Zealand")
    NICARAGUA = ("NICARAGUA", "Nicaragua")
    NIGER = ("NIGER", "Niger")
    NIGERIA = ("NIGERIA", "Nigeria")
    NORTH = ("NORTH", "North Korea")
    NORTH = ("NORTH", "North Macedonia")
    NORWAY = ("NORWAY", "Norway")
    OMAN = ("OMAN", "Oman")
    PAKISTAN = ("PAKISTAN", "Pakistan")
    PALAU = ("PALAU", "Palau")
    PANAMA = ("PANAMA", "Panama")
    PAPUA = ("PAPUA", "Papua New Guinea")
    PARAGUAY = ("PARAGUAY", "Paraguay")
    PERU = ("PERU", "Peru")
    PHILIPPINES = ("PHILIPPINES", "Philippines")
    POLAND = ("POLAND", "Poland")
    PORTUGAL = ("PORTUGAL", "Portugal")
    QATAR = ("QATAR", "Qatar")
    ROMANIA = ("ROMANIA", "Romania")
    RUSSIA = ("RUSSIA", "Russia")
    RWANDA = ("RWANDA", "Rwanda")
    SAMOA = ("SAMOA", "Samoa")
    SAN = ("SAN", "San Marino")
    SAO = ("SAO", "Sao Tome and Principe")
    SAUDI = ("SAUDI", "Saudi Arabia")
    SENEGAL = ("SENEGAL", "Senegal")
    SERBIA = ("SERBIA", "Serbia")
    SEYCHELLES = ("SEYCHELLES", "Seychelles")
    SIERRA = ("SIERRA", "Sierra Leone")
    SINGAPORE = ("SINGAPORE", "Singapore")
    SLOVAKIA = ("SLOVAKIA", "Slovakia")
    SLOVENIA = ("SLOVENIA", "Slovenia")
    SOLOMON = ("SOLOMON", "Solomon Islands")
    SOMALIA = ("SOMALIA", "Somalia")
    SOUTH_AFRICA = ("SOUTH_AFRICA", "South Africa")
    SOUTH_KOREA = ("SOUTH_KOREA", "South Korea")
    SOUTH_SUDAN = ("SOUTH_SUDAN", "South Sudan")
    SPAIN = ("SPAIN", "Spain")
    SRI_LANKA = ("SRI_LANKA", "Sri Lanka")
    STKITTS = ("STKITTS", "St Kitts and Nevis")
    STLUCIA = ("STLUCIA", "St Lucia")
    STVINCENT = ("STVINCENT", "St Vincent")
    SUDAN = ("SUDAN", "Sudan")
    SURINAME = ("SURINAME", "Suriname")
    SWEDEN = ("SWEDEN", "Sweden")
    SWITZERLAND = ("SWITZERLAND", "Switzerland")
    SYRIA = ("SYRIA", "Syria")
    TAJIKISTAN = ("TAJIKISTAN", "Tajikistan")
    TANZANIA = ("TANZANIA", "Tanzania")
    THAILAND = ("THAILAND", "Thailand")
    BAHAMAS = ("BAHAMAS", "The Bahamas")
    GAMBIA = ("GAMBIA", "The Gambia")
    TOGO = ("TOGO", "Togo")
    TONGA = ("TONGA", "Tonga")
    TRINIDAD = ("TRINIDAD", "Trinidad and Tobago")
    TUNISIA = ("TUNISIA", "Tunisia")
    TURKEY = ("TURKEY", "Turkey")
    TURKMENISTAN = ("TURKMENISTAN", "Turkmenistan")
    TUVALU = ("TUVALU", "Tuvalu")
    UGANDA = ("UGANDA", "Uganda")
    UKRAINE = ("UKRAINE", "Ukraine")
    UAE = ("UAE", "United Arab Emirates")
    UK = ("UK", "United Kingdom")
    US = ("US", "United States")
    URUGUAY = ("URUGUAY", "Uruguay")
    USSR = ("USSR", "USSR")
    UZBEKISTAN = ("UZBEKISTAN", "Uzbekistan")
    VANUATU = ("VANUATU", "Vanuatu")
    VATICAN = ("VATICAN", "Vatican City")
    VENEZUELA = ("VENEZUELA", "Venezuela")
    VIETNAM = ("VIETNAM", "Vietnam")
    YEMEN = ("YEMEN", "Yemen")
    YUGOSLAVIA = ("YUGOSLAVIA", "Yugoslavia")
    ZAMBIA = ("ZAMBIA", "Zambia")
    ZIMBABWE = ("ZIMBABWE", "Zimbabwe")


class Region(Choices):
    DEFAULT = ("DEFAULT", "----")
    AMERICAS = ("AMERICAS", "Americas")
    APAC = ("APAC", "Asia-Pacific")
    EMEA = ("EMEA", "EMEA")


class RequestForCall(Choices):
    DEFAULT = ("DEFAULT", "----")
    YES_MORNING = ("YES_MORNING", "Yes - morning")
    YES_AFTERNOON = ("YES_AFTERNOON", "Yes - afternoon")
    YES_OTHER = ("YES_OTHER", "Yes - other")
    NO = ("NO", "No")


class FirstResponseChannel(Choices):
    DEFAULT = ("DEFAULT", "----")
    CALL = ("CALL", "Call")
    EMAIL = ("EMAIL", "Email")
    NOT_RESPONDED = ("NOT_RESPONDED", "Not yet responded")


class HpoSelection(Choices):
    DEFAULT = ("DEFAULT", "----")
    FOOD_PRODUCTION = ("FOOD_PRODUCTION", "Food Production")
    UK_RAIL = ("UK_RAIL", "UK Rail")
    LIGHTWEIGHT_STRUCTURES = ("LIGHTWEIGHT_STRUCTURES", "Lightweight Structures")


class OrganisationType(Choices):
    DEFAULT = ("DEFAULT", "----")
    CHARITY = ("CHARITY,", "Charity")
    GOVERNMENT = ("GOVERNMENT", "Government department or other public body")
    LIMITED_COMPANY = ("LIMITED_COMPANY", "Limited company")
    LIMITED_PARTNERSHIP = ("LIMITED_PARTNERSHIP", "Limited partnership")
    PARTNERSHIP = ("PARTNERSHIP,", "Partnership")
    SOLE_TRADER = ("SOLE_TRADER", "Sole trader")


class InvestmentType(Choices):
    DEFAULT = ("DEFAULT", "----")
    ACQUISITION = ("ACQUISITION", "Acquisition")
    CAPITAL_ONLY = ("CAPITAL_ONLY", "Capital only")
    NEW_SITE = ("NEW_SITE", "Creation of new site or activity")
    EXPANSION = ("EXPANSION", "Expansion of existing site or activity")
    JOINT_VENTURE = ("JOINT_VENTURE", "Joint venture")
    MERGER = ("MERGER", "Merger")
    RETENTION = ("RETENTION", "Retention")
    NOT_SPECIFIED = ("NOT_SPECIFIED", "Not specified")


class NewExistingInvestor(Choices):
    DEFAULT = ("DEFAULT", "----")
    NEW = ("NEW,", "New investor")
    EXISTING = ("EXISTING,", "Existing investor")


class InvestorInvolvement(Choices):
    FDI_HUB_HQ = ("FDI_HUB_HQ", "FDI Hub + HQ")
    FDI_HUB_HQ_LEP = ("FDI_HUB_HQ_LEP", "FDI Hub + HQ + LEP")
    FDI_HUB_POST_LEP = ("FDI_HUB_POST_LEP", "FDI Hub + HQ + Post + LEP")
    FDI_HUB_POST_REG = ("FDI_HUB_POST_REG", "FDI Hub + HQ + Post + Reg")
    FDI_HUB_HQ_REG = ("FDI_HUB_HQ_REG", "FDI Hub + HQ  + Reg")
    FDI_HUB_LEP = ("FDI_HUB_LEP", "FDI Hub + LEP")
    FDI_HUB_POST = ("FDI_HUB_POST", "FDI Hub + Post")
    FDI_HUB_POST_HQ = ("FDI_HUB_POST_HQ", "FDI Hub + Post + HQ")
    FDI_HUB_POST_LEP = ("FDI_HUB_POST_LEP", "FDI Hub + Post + LEP")
    FDI_HUB_POST_REG = ("FDI_HUB_POST_REG", "FDI Hub + Post + Reg")
    FDI_HUB_REGION = ("FDI_HUB_REGION", "FDI Hub + Region")
    FDI_HUB_ONLY = ("FDI_HUB_ONLY", "FDI Hub Only")
    HQ_LEP = ("HQ_LEP", "HQ + LEP")
    HQ_POST_LEP = ("HQ_POST_LEP", "HQ + Post + LEP")
    HQ_ONLY = ("HQ_ONLY", "HQ Only")
    HQ_POST_ONLY = ("HQ_POST_ONLY", "HQ and Post Only")
    HQ_REGION = ("HQ_REGION", "HQ and Region")
    HQ_POST_REGION = ("HQ_POST_REGION,", "HQ, Post and Region")
    LEP_ONLY = ("LEP_ONLY", "LEP Only")
    NO_INVOLVEMENT = ("NO_INVOLVEMENT", "No involvement")
    POST_LEP = ("POST_LEP", "Post + LEP")
    POST_ONLY = ("POST_ONLY", "Post Only")
    POST_REGION = ("POST_REGION", "Post and Region")
    REGION_ONLY = ("REGION_ONLY", "Region Only")


class InvestmentProgramme(Choices):
    ADVANCED_ENG = ("ADVANCED_ENG", "Advanced Engineering Supply Chain")
    BUSINESS_PARTNER = ("BUSINESS_PARTNER", "Business Partnership (Non-FDI)")
    CONTRACT_RESEARCH = ("CONTRACT_RESEARCH", "Contract Research (Non-FDI)")
    FDI_CAPITAL_ONLY = ("FDI_CAPITAL_ONLY", "FDI (Capital Only)")
    GREAT_INV_PROG = ("GREAT_INV_PROG", "GREAT Investors Programme")
    GLOBAL_ENTREP_PROG = ("GLOBAL_ENTREP_PROG", "Global Entrepreneur Programme")
    GRADUATE_ENTREP_PROG = ("GRADUATE_ENTREP_PROG", "Graduate Entrepreneur Programme")
    HQ_UK = ("HQ_UK", "HQ-UK")
    II_AND_I = ("II&I", "II&I Programme")
    INFRASTRUCTURE_GATEWAY = ("INFRASTRUCTURE_GATEWAY", "Infrastructure Gateway")
    IIGB = ("IIGB", "Invest in Great Britain")
    NO_SPECIFIC_PROG = ("NO_SPECIFIC_PROG", "No Specific Programme")
    RD_COLLAB = ("R&D_COLLAB", "R&D Collaboration (Non-FDI)")
    RD_PARTNERSHIP = ("R&D_PARTNERSHIP", "R&D Partnership (Non-FDI)")
    RD_PROG = ("R&D_PROG", "R&D Prog (Obsolete)")
    REGENERATION = ("REGENERATION", "Regeneration Investment Organisation (RIO)")
    SRM = ("SRM", "SRM Programme")
    SCREEN = ("SCREEN", "Screen Production Investment")
    SIRIUS = ("SIRIUS", "Sirius (Graduate Entrepreneurs)")
    SPACE = ("SPACE", "Space")
    UNIVERSITY_COLLAB = ("UNIVERSITY_COLLAB", "University Collaboration (Non-FDI)")
    VENTURE_CAPITAL = ("VENTURE_CAPITAL", "Venture / Equity Capital")


class DatahubProjectStatus(Choices):
    DEFAULT = ("DEFAULT", "----")
    PROSPECT = ("PROSPECT", "Prospect")
    ASSIGN = ("ASSIGN", "Assign PM")
    ACTIVE = ("ACTIVE", "Active")
    VERIFY = ("VERIFY", "Verify Win")
    WON = ("WON", "Won")
    ABANDONED = ("ABANDONED", "Abandoned")
    DELAYED = ("DELAYED", "Delayed")
