# Generated by Django 3.0.3 on 2020-03-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiries", "0003_auto_20200309_1531"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquirer",
            name="email",
            field=models.EmailField(blank=True, max_length=255, verbose_name="Email"),
        ),
    ]
