# Generated by Django 3.0.3 on 2020-03-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0004_auto_20200310_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='crm',
            field=models.CharField(blank=True, help_text='Name of the relationship manager', max_length=255, null=True, verbose_name='CRM'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
