# Generated by Django 3.0.3 on 2020-03-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0004_auto_20200310_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='dh_company_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company id in Data Hub'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='dh_assigned_company',
            field=models.CharField(blank=True, help_text='Name of the company in Data Hub', max_length=255, null=True, verbose_name='Company in Data Hub'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='dh_company_address',
            field=models.CharField(blank=True, help_text='Address of the company in Data Hub', max_length=255, null=True, verbose_name='Company address in Data Hub'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='dh_company_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company number in Data Hub'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='dh_duns_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Duns number'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='new_existing_investor',
            field=models.CharField(choices=[('DEFAULT', '----'), ('NEW', 'New investor'), ('EXISTING', 'Existing investor')], default='DEFAULT', max_length=255, verbose_name='New or existing investor'),
        ),
    ]
