# Generated by Django 3.0.3 on 2020-03-29 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0005_auto_20200323_1901'),
        ('enquiries', '0005_auto_20200318_1027'),
    ]

    operations = [
    ]
