# Generated by Django 3.0.3 on 2020-03-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0005_auto_20200323_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(blank=True, help_text='Index of the object', max_length=255, null=True)),
                ('object_id', models.CharField(blank=True, help_text='Id of the failed object', max_length=255, null=True)),
                ('html_body', models.TextField(blank=True, null=True, verbose_name='HTML body')),
                ('text_body', models.TextField(blank=True, null=True, verbose_name='Text body')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedEnquiryCursor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(blank=True, help_text='Index of the object', max_length=255, null=True)),
                ('object_id', models.CharField(blank=True, help_text='Id of the last object in the results returned by AS corresponding to the index', max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='new_existing_investor',
            field=models.CharField(choices=[('DEFAULT', '----'), ('NEW', 'New investor'), ('EXISTING', 'Existing investor')], default='DEFAULT', max_length=255, verbose_name='New or existing investor'),
        ),
    ]
