# Generated by Django 3.0.3 on 2020-03-25 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0005_auto_20200322_0049'),
        ('enquiries', '0005_auto_20200323_1901'),
    ]

    operations = [
    ]
