# Generated by Django 3.0.3 on 2020-03-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0006_merge_20200329_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='new_existing_investor',
            field=models.CharField(choices=[('DEFAULT', '----'), ('NEW', 'New investor'), ('EXISTING', 'Existing investor')], default='DEFAULT', max_length=255, verbose_name='New or existing investor'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='primary_sector',
            field=models.CharField(choices=[('DEFAULT', '----'), ('ADVANCED_ENG', 'Advanced Engineering'), ('AEROSPACE', 'Aerospace'), ('AGRICULTURE', 'Agriculture, Horticulture, Fisheries and Pets'), ('AIRPORTS', 'Airports'), ('AUTOMOTIVE', 'Automotive'), ('CHEMICALS', 'Chemicals'), ('CONSTRUCTION', 'Construction'), ('CONSUMER', 'Consumer and Retail'), ('CREATIVE', 'Creative Industries'), ('CYBER', 'Cyber Security'), ('DEFENCE', 'Defence'), ('EDUCATION', 'Education and Training'), ('ENERGY', 'Energy'), ('ENVIRONMENT', 'Environment'), ('FINANCIAL', 'Financial and Professional Services'), ('FOOD', 'Food and Drink'), ('HEALTHCARE', 'Healthcare Services'), ('MARITIME', 'Maritime'), ('MEDICAL', 'Medical Devices and Equipment'), ('MINING', 'Mining'), ('PHARMACEUTICALS', 'Pharmaceuticals and Biotechnology'), ('RAILWAYS', 'Railways'), ('SECURITY', 'Security'), ('SPACE', 'Space'), ('SPORTS', 'Sports Economy'), ('TECHNOLOGY', 'Technology and Smart Cities'), ('WATER', 'Water')], default='DEFAULT', max_length=255, verbose_name='Primary sector'),
        ),
    ]
