# Generated by Django 3.0.3 on 2020-03-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0006_merge_20200325_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='dh_assigned_company',
            new_name='dh_assigned_company_name',
        ),
        migrations.AddField(
            model_name='enquirer',
            name='country_code',
            field=models.CharField(default='', max_length=5, verbose_name='Country code'),
            preserve_default=False,
        ),
    ]
