# Generated by Django 3.0.3 on 2020-04-01 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0007_auto_20200329_0356'),
        ('enquiries', '0007_auto_20200326_1246'),
    ]

    operations = [
    ]
