# Generated by Django 3.0.3 on 2020-03-29 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0006_merge_20200329_0018'),
        ('enquiries', '0007_auto_20200326_1246'),
    ]

    operations = [
    ]
