# Generated by Django 3.0.3 on 2020-04-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0008_merge_20200401_0400'),
        ('enquiries', '0008_merge_20200329_0239'),
    ]

    operations = [
    ]
