# Generated by Django 3.0.3 on 2020-04-01 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0008_merge_20200401_0400'),
        ('enquiries', '0008_merge_20200401_0549'),
    ]

    operations = [
    ]
