# Generated by Django 3.0.3 on 2020-04-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0008_merge_20200329_0239'),
        ('enquiries', '0008_auto_20200402_1148'),
    ]

    operations = [
    ]
