# Generated by Django 3.0.3 on 2020-04-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0009_enquirer_country_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='enquirer',
            name='country_code',
        ),
        migrations.AddField(
            model_name='enquirer',
            name='phone_country_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Telephone country code'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_stage',
            field=models.CharField(choices=[('NEW', 'New'), ('AWAITING_RESPONSE', 'Awaiting response from Investor'), ('ENGAGED', 'Engaged in dialogue'), ('NON_RESPONSIVE', 'Non-responsive'), ('NON_FDI', 'Non-FDI'), ('ADDED_TO_DATAHUB', 'Added to Data Hub'), ('SENT_TO_POST', 'Sent to Post'), ('POST_PROGRESSING', 'Post progressing')], default='NEW', max_length=255, verbose_name='Enquiry stage'),
        ),
    ]
