# Generated by Django 3.0.7 on 2020-06-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0010_auto_20200406_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='crm',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='client_relationship_manager',
            field=models.CharField(blank=True, help_text='Name of the client relationship manager', max_length=255, null=True, verbose_name='Client Relationship Manager'),
        ),
    ]
