# Generated by Django 3.0.7 on 2020-06-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0011_rename_crm_field_client_relationship_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='website',
            field=models.TextField(blank=True, default='', verbose_name='Website'),
            preserve_default=False,
        ),
    ]
