# Generated by Django 3.0.7 on 2020-07-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0012_change_website_field_to_text_field_no_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_text',
            field=models.TextField(editable=False, verbose_name='Enquiry text'),
        ),
    ]
