# Generated by Django 3.0.7 on 2020-08-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0016_add_non_applicable_enquiry_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='investor_involvement_level',
            field=models.CharField(choices=[('FDI_HUB_HQ', 'FDI Hub + HQ'), ('FDI_HUB_HQ_LEP', 'FDI Hub + HQ + LEP'), ('FDI_HUB_HQ_POST_LEP', 'FDI Hub + HQ + Post + LEP'), ('FDI_HUB_HQ_POST_REG', 'FDI Hub + HQ + Post + Reg'), ('FDI_HUB_HQ_REG', 'FDI Hub + HQ  + Reg'), ('FDI_HUB_LEP', 'FDI Hub + LEP'), ('FDI_HUB_POST', 'FDI Hub + Post'), ('FDI_HUB_POST_HQ', 'FDI Hub + Post + HQ'), ('FDI_HUB_POST_LEP', 'FDI Hub + Post + LEP'), ('FDI_HUB_POST_REG', 'FDI Hub + Post + Reg'), ('FDI_HUB_REGION', 'FDI Hub + Region'), ('FDI_HUB_ONLY', 'FDI Hub Only'), ('HQ_LEP', 'HQ + LEP'), ('HQ_POST_LEP', 'HQ + Post + LEP'), ('HQ_ONLY', 'HQ Only'), ('HQ_POST_ONLY', 'HQ and Post Only'), ('HQ_REGION', 'HQ and Region'), ('HQ_POST_REGION,', 'HQ, Post and Region'), ('LEP_ONLY', 'LEP Only'), ('NO_INVOLVEMENT', 'No Involvement'), ('POST_LEP', 'Post + LEP'), ('POST_ONLY', 'Post Only'), ('POST_REGION', 'Post and Region'), ('REGION_ONLY', 'Region Only')], default='FDI_HUB_POST', max_length=255, verbose_name='Investor level of involvement'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='new_existing_investor',
            field=models.CharField(choices=[('DEFAULT', '----'), ('NEW', 'New Investor'), ('EXISTING', 'Existing Investor')], default='DEFAULT', max_length=255, verbose_name='New or existing investor'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='specific_investment_programme',
            field=models.CharField(choices=[('ADVANCED_ENG', 'Advanced Engineering Supply Chain'), ('BUSINESS_PARTNER', 'Business Partnership (Non-FDI)'), ('CONTRACT_RESEARCH', 'Contract Research (Non-FDI)'), ('EMERGING_MARKETS_GULF', 'Emerging Markets Contract (Gulf)'), ('EMERGING_MARKETS_RUSSIA', 'Emerging Markets Contract (Russia)'), ('FDI_CAPITAL_ONLY', 'FDI (Capital Only)'), ('GLOBAL_ENTREP_PROG', 'Global Entrepreneur Programme'), ('GRADUATE_ENTREP_PROG', 'Graduate Entrepreneur Programme'), ('GREAT_INV_PROG', 'GREAT Investors Programme'), ('HQ_UK', 'HQ-UK'), ('II&I', 'II&I Programme'), ('INFRASTRUCTURE_INVESTMENT', 'Infrastructure Investment'), ('INNOVATION_GATEWAY', 'Innovation Gateway'), ('IIGB', 'Invest in GREAT Britain'), ('NO_SPECIFIC_PROG', 'No Specific Programme'), ('R&D_COLLAB', 'R&D Collaboration (Non-FDI)'), ('R&D_PARTNERSHIP', 'R&D Partnership (Non-FDI)'), ('R&D_PROG', 'R&D Prog (Obsolete)'), ('REGENERATION', 'Regeneration Investment Organisation (RIO)'), ('SCREEN', 'Screen Production Investment'), ('SIRIUS', 'Sirius (Graduate Entrepreneurs)'), ('SPACE', 'Space'), ('SRM', 'SRM Programme'), ('UNIVERSITY_COLLAB', 'University Collaboration (Non-FDI)'), ('VENTURE_CAPITAL', 'Venture / Equity Captial')], default='IIGB', max_length=255, verbose_name='Specific investment programme'),
        ),
    ]
