# Generated by Django 3.0.7 on 2020-08-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0017_update_investment_field_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
