# Generated by Django 3.0.7 on 2020-08-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0018_enquiry_date_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirer',
            name='email',
            field=models.TextField(blank=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='enquirer',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='enquirer',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='company_name',
            field=models.CharField(blank=True, help_text='Name of the company', max_length=255, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='investment_readiness',
            field=models.CharField(blank=True, choices=[('DEFAULT', '----'), ('CONVINCED', 'I’m convinced and want to talk to someone about my plans'), ('SHORTLIST', 'The UK is on my shortlist. How can the Department for International Trade help me?'), ('EXPLORING', 'I’m still exploring where to expand my business and would like to know more about the UK’s offer'), ('NOT_READY', 'I’m not yet ready to invest. Keep me informed'), ('NOT_INTERESTED_IN_UK', 'I’m not interested in setting up in the UK')], default='DEFAULT', max_length=255, verbose_name='Investment readiness'),
        ),
    ]
