# Generated by Django 3.0.7 on 2020-08-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0019_reduce_validation_for_csv_input_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='region',
            field=models.CharField(choices=[('DEFAULT', '----'), ('AMERICAS', 'Americas'), ('APAC', 'Asia-Pacific'), ('EMEA', 'EMEA'), ('UK', 'UK')], default='DEFAULT', max_length=255, verbose_name='Region'),
        ),
    ]
