# Generated by Django 3.0.7 on 2020-09-14 00:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0020_add_uk_to_region_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('EMAIL_CAMPAIGN_SUBSCRIBE', 'Subscribe to email campaign')], default='EMAIL_CAMPAIGN_SUBSCRIBE', max_length=150)),
                ('actioned_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('action_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enquiries.Enquiry')),
            ],
        ),
    ]
