# Generated by Django 3.2.19 on 2023-06-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0024_auto_20220621_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='how_they_heard_dit',
            field=models.CharField(choices=[('DEFAULT', '----'), ('PRESS_AD', 'Press ad (newspaper/trade publication'), ('OUTDOOR_AD', 'Outdoor ad/billboard'), ('LINKEDIN', 'LinkedIn'), ('SOCIAL_MEDIA', 'Other social media (e.g. Twitter/Facebook)'), ('INTERNET_SEARCH', 'Internet search'), ('OTHER', 'Other')], default='DEFAULT', max_length=255, verbose_name='How did they hear about DBT?'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='investment_readiness',
            field=models.CharField(blank=True, choices=[('DEFAULT', '----'), ('CONVINCED', 'I’m convinced and want to talk to someone about my plans'), ('SHORTLIST', 'The UK is on my shortlist. How can the Department for Business and Trade help me?'), ('EXPLORING', 'I’m still exploring where to expand my business and would like to know more about the UK’s offer'), ('NOT_READY', 'I’m not yet ready to invest. Keep me informed'), ('NOT_INTERESTED_IN_UK', 'I’m not interested in setting up in the UK')], default='DEFAULT', max_length=255, verbose_name='Investment readiness'),
        ),
    ]
